# Generated by Django 4.2.23 on 2026-03-31 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0004_alter_comment_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='is_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('smoke', '흡연 실수'), ('overeat', '과식/폭식'), ('drink', '음주'), ('lazy', '운동 부족')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ai_advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
