# Generated by Django 4.2.23 on 2026-03-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_healthprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='recommended_food',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='shop_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='event_type',
            field=models.CharField(max_length=20),
        ),
    ]
