# Generated by Django 4.2.23 on 2026-03-31 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_behaviorlog_recommended_food_behaviorlog_shop_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviorlog',
            name='description',
        ),
    ]
