# Generated by Django 4.2.23 on 2026-03-31 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0009_recipe_author_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='expert_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
