# Generated by Django 4.2.23 on 2026-03-31 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0010_behaviorlog_description_behaviorlog_expert_tip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='status',
            field=models.CharField(choices=[('waiting', 'AI 분석 대기중'), ('ai_completed', 'AI 처방 완료'), ('expert_completed', '전문가 상담 완료')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='ai_advice',
            field=models.TextField(blank=True, verbose_name='AI 조언'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='description',
            field=models.TextField(verbose_name='나의 상황 설명'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='event_type',
            field=models.CharField(max_length=20, verbose_name='실수 종류'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='expert_tip',
            field=models.TextField(blank=True, verbose_name='전문가 한마디'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
