# Generated by Django 4.2.23 on 2026-03-31 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0011_behaviorlog_status_alter_behaviorlog_ai_advice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviorlog',
            name='status',
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='ai_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='event_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='expert_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(default=0, verbose_name='신장'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(default=0, verbose_name='기본 체중'),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(verbose_name='오늘의 체중')),
                ('steps', models.IntegerField(default=0, verbose_name='걸음 수')),
                ('alcohol_cups', models.IntegerField(default=0, verbose_name='음주량(잔)')),
                ('smoking_sticks', models.IntegerField(default=0, verbose_name='흡연량(개비)')),
                ('memo', models.TextField(blank=True, verbose_name='오늘의 메모')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
