# Generated by Django 4.2.23 on 2026-03-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_remove_behaviorlog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='bp_diastolic',
            field=models.IntegerField(default=0, verbose_name='이완기 혈압'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='bp_systolic',
            field=models.IntegerField(default=0, verbose_name='수축기 혈압'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='알레르기 정보'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='기저질환 (고혈압, 당뇨 등)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='긴급 연락처', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='alcohol_cups',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='smoking_sticks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='weight',
            field=models.FloatField(verbose_name='체중(kg)'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
