# Generated by Django 4.2.23 on 2026-04-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_dailylog_bp_diastolic_dailylog_bp_systolic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviorlog',
            name='recommended_food',
        ),
        migrations.RemoveField(
            model_name='behaviorlog',
            name='shop_url',
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='breakfast',
            field=models.CharField(blank=True, max_length=200, verbose_name='아침'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='dinner',
            field=models.CharField(blank=True, max_length=200, verbose_name='저녁'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='lunch',
            field=models.CharField(blank=True, max_length=200, verbose_name='점심'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='bp_diastolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='bp_systolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='blood_type',
            field=models.CharField(choices=[('미설정', '미설정'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='미설정', max_length=5),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
