# Generated by Django 4.2.23 on 2026-04-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_remove_behaviorlog_recommended_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='recommended_food',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='shop_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='breakfast',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='dinner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='lunch',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
