# Generated by Django 4.2.23 on 2026-04-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_behaviorlog_recommended_food_behaviorlog_shop_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='sleep_hours',
            field=models.FloatField(default=0.0, verbose_name='수면시간'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='stress_level',
            field=models.IntegerField(default=5, verbose_name='스트레스(1-10)'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='bp_diastolic',
            field=models.IntegerField(default=0, verbose_name='이완기혈압'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='bp_systolic',
            field=models.IntegerField(default=0, verbose_name='수축기혈압'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='알레르기'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, verbose_name='기저질환'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='긴급연락처'),
        ),
    ]
