# Generated by Django 4.2.23 on 2026-04-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_dailylog_sleep_hours_dailylog_stress_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='본인 연락처'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='bp_diastolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='bp_systolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='sleep_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='stress_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='비상 연락처'),
        ),
    ]
