# Generated by Django 4.2.23 on 2026-04-01 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0017_healthprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='긴급연락처'),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='약/영양제 이름')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='복용량')),
                ('time_to_take', models.TimeField(blank=True, null=True, verbose_name='복용 시간')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
