# Generated by Django 4.2.23 on 2026-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_alter_healthprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='water_ml',
            field=models.IntegerField(default=0, verbose_name='수분 섭취(ml)'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='expected_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='출산 예정일'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='is_pregnant',
            field=models.BooleanField(default=False, verbose_name='임신 여부'),
        ),
    ]
