# Generated by Django 4.2.23 on 2026-04-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_dailylog_water_ml_healthprofile_expected_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성'), ('U', '미설정')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='water_ml',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='expected_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
