# Generated by Django 4.2.23 on 2026-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_healthprofile_gender_alter_dailylog_water_ml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
