# Generated by Django 4.2.23 on 2026-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0022_alter_medication_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
