# Generated by Django 4.2.23 on 2026-04-03 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0023_alter_medication_dosage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoked_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-smoked_at'],
            },
        ),
    ]
